### ISSUE TITLE
Propsoal Logo/Icon

### ISSUE THREAD

**Issue by amirdesaingrafis** [j4velin/MapsMeasure#11]
Hello, I want to contribute to this awesome project, and I have a new logo design for you, if you allowed I will send to you :)

**Comment by j4velin** [comment]
Sure

amirdesaingrafis <notifications@github.com> schrieb am Di., 8. Mai 2018,
10:06:

**Comment by amirdesaingrafis** [comment]
Thankyou for the response
I will give a little revision to the old logo with a clean and minimalist new logo

**Comment by amirdesaingrafis** [comment]
Hi @j4velin 
![01](https://user-images.githubusercontent.com/36655856/39751315-fe48f59a-52e1-11e8-818e-4dc85fb19b5d.png)
![02](https://user-images.githubusercontent.com/36655856/39751327-054ddf54-52e2-11e8-947d-013b42a327a4.png)

I design it from the two-letter abbreviation "M" inside the globe and in the center I combine a ruler (gauge) that represents the size of one place to another.

**Comment by j4velin** [comment]
Thanks!

amirdesaingrafis <notifications@github.com> schrieb am Di., 8. Mai 2018 um
12:05 Uhr:

**Comment by amirdesaingrafis** [comment]
What do you think. if there is a revision I will do as soon as possible

**Comment by j4velin** [comment]
Pretty good, thanks. Can you provide a 512x512 px version of the "blue with white background" one?

**Comment by amirdesaingrafis** [comment]
I will send, please wait

**Comment by amirdesaingrafis** [comment]
https://drive.google.com/open?id=1wk_uc3ajVOukZSbYbi1nqgkJKRyfZT2L

**Comment by amirdesaingrafis** [comment]
I already send the file icon 512x512, what do you think?

**Comment by j4velin** [comment]
Added in https://github.com/j4velin/MapsMeasure/commit/0cd447f1a22529c72fb294a020f73938d33a6e18
