### ISSUE TITLE
Provide an apk on Github

### ISSUE THREAD

**Issue by Poussinou** [j4velin/MapsMeasure#8]
Can you please provide an apk for each release you're doing as described [here](https://help.github.com/articles/creating-releases/). It will be useful for people like me who don't use Google Play Services...

Regards

**Comment by j4velin** [comment]
Sorry, but I dont think that'll work as the app relies on Google Play Services and I doubt that it'll run on a device without them

**Comment by Poussinou** [comment]
Hum I don't know. Can we try? Otherwise that's ok :)
